name: Crear release al crear un tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Obtener el último tag
        id: get_last_tag
        run: |
          last_tag=$(git describe --tags --abbrev=0)
          echo "last_tag=$last_tag" >> $GITHUB_ENV

      - name: Obtener commits desde el último tag
        id: get_commits
        run: |
          commits=$(git log ${last_tag}..HEAD --pretty=format:"- %s (%an)")
          echo "commits=$commits" >> $GITHUB_ENV

      - name: Crear la release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            **Changelog:**
            ${{ env.commits }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
