name: Create Release with Template and Git Log

on:
  push:
    tags:
      - "v*.*.*" # Escucha tags en formato semántico

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate Git Log Changelog
        id: generate-changelog
        run: |
          # Obtiene el último tag antes del actual
          last_tag=$(git describe --tags --abbrev=0)
          # Genera el changelog basado en commits desde el último tag
          log=$(git log ${last_tag}..HEAD --pretty=format:"- %s (%an, %h)")
          echo "Changelog desde $last_tag:" > changelog.md
          echo "$log" >> changelog.md
          # Exporta el contenido del changelog a una variable de entorno
          echo "release_body=$(cat changelog.md)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ env.release_body }} # Asigna la variable generada al body
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
