name: Crear release al crear un tag

on:
  push:
    tags:
      - "v*" # Detectar tags con formato semántico

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Obtener el último tag anterior
        id: get_last_tag
        run: |
          last_tag=$(git tag --list --sort=-creatordate | sed -n '2p')
          echo "Previous tag: $last_tag"
          echo "last_tag=$last_tag" >> $GITHUB_ENV

      - name: Generar el changelog
        id: generate_changelog
        run: |
          # Obtener todos los commits entre el tag anterior y el actual
          commits=$(git log ${{env.last_tag}}..${{ github.ref_name }} --pretty=format:"- %s (%an)")
          echo "Previous tag: ${{env.last_tag}} // Current tag: ${{github.ref_name}}"
          echo "Changelog generado: $commits"
          echo "commits=$commits" >> $GITHUB_ENV

      - name: Verificar el changelog generado
        run: |
          echo "Changelog generado: ${{ env.commits }}"

      - name: Crear la release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            **Changelog:**
            ${{ env.commits }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
