name: Create Release with Template and Git Log

on:
  push:
    tags:
      - "v*.*.*" # Escucha tags en formato semántico

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate Git Log Changelog
        id: generate-changelog
        run: |
          last_tag=$(git describe --tags --abbrev=0)
          log=$(git log ${last_tag}..HEAD --pretty=format:"- %s (%an, %h)")
          echo "$log" > changelog.md
          echo "changelog=$(cat changelog.md)" >> $GITHUB_ENV

      - name: Load Release Template
        id: load-template
        run: |
          template=$(cat release-template.md)
          template=${template//\{\{tag_name\}\}/${{ github.ref_name }}}
          changelog=$(cat changelog.md)
          template=${template//\{\{changelog\}\}/${changelog}}
          echo "release_body=$template" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }} # Usa el tag como nombre
          release_name: ${{ github.ref_name }} # Usa el tag como nombre de la release
          body: ${{ env.release_body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Añadir el token aquí
