name: Crear release al crear un tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Obtener información del tag
        id: get_tag
        run: tag_name=$(git describe --tags --abbrev=0)
      - name: Obtener commits desde el último tag
        id: get_commits
        run: |
          last_tag=$(steps.get_tag.outputs.tag_name)
          commits=$(git log --pretty=format:%s --since="$last_tag" HEAD)
      - name: Crear la release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.tag_name }}
          release_name: Release ${{ github.tag_name }}
          body: |
            **Changelog:**
            ${{ github.commits }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
