name: Crear release al crear un tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Obtener el último tag anterior al actual
        id: get_last_tag
        run: |
          if git describe --tags --abbrev=0 HEAD^ >/dev/null 2>&1; then
            last_tag=$(git describe --tags --abbrev=0 HEAD^)
          else
            last_tag=""
          fi
          echo "last_tag=$last_tag" >> $GITHUB_ENV

      - name: Generar el changelog desde el último tag
        id: generate_changelog
        run: |
          if [ -z "${{ env.last_tag }}" ]; then
            commits=$(git log --pretty=format:"- %s (%an)")
          else
            commits=$(git log ${env.last_tag}..HEAD --pretty=format:"- %s (%an)")
          fi
          echo "commits=$commits" >> $GITHUB_ENV

      - name: Verificar el changelog generado
        run: |
          echo "Changelog generado: ${{ env.commits }}"

      - name: Crear la release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            **Changelog:**
            ${{ env.commits }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
