name: Crear release al crear un tag

on:
  push:
    tags:
      - "v*" # Detectar tags con formato semántico

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Obtener el último tag anterior
        id: get_last_tag
        run: |
          last_tag=$(git tag --list --sort=-creatordate | sed -n '2p')
          echo "Previous tag: $last_tag"
          echo "last_tag=$last_tag" >> $GITHUB_ENV

      - name: Generar changelog
        id: generate_changelog
        run: |
          # Generar el changelog y guardarlo en un archivo temporal
          changelog=$(git log ${{env.last_tag}}..${{ github.ref_name }} --pretty=format:"- %s ([%h](https://github.com/${{ github.repository }}/commit/%H)) (%an)")
          {
            echo 'changelog<<EOF'
            echo "$changelog"
            echo 'EOF'
            } >> $GITHUB_ENV

      - name: Crear la release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            **Changelog:**
            ${{env.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
